version: '3'

services:
  webserver:
    container_name: media
    image: ebm17915/media:latest
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html

  composer:
    restart: 'no'
    container_name: media_composer
    image: composer:latest
    command: install 
    volumes:
      - .:/app/
